"""create payments table

Revision ID: 4e812341edd5
Revises:
Create Date: 2026-09-02 19:44:40.034293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e812341edd5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "currency IN ('BRL', 'USD', 'JPY')", name=op.f("ck_payments_currency_supported")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RISK_REVIEW', 'APPROVED', 'REJECTED')",
            name=op.f("ck_payments_status_valid"),
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_payments_amount_minor_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    # ### end Alembic commands ###
